# A sample Guardfile
# More info at https://github.com/guard/guard#readme


guard 'livereload' do
  watch(%r{.+\.(html)})
  watch(%r{stylesheets/.+\.(css)})
end

guard 'haml' do
  watch(%r{^.+(\.haml)})
end

guard 'compass' do
  watch(%r{.s[ac]ss})
end
